### ISSUE TITLE
[Question] CSS variables support?

### ISSUE THREAD

**Issue by thednp** [dgrammatiko/sass-worker#1]
Hey @dgrammatiko, I hope you're all right :)

Does this support CSS variables? If so, can this work with SCSS mixins? Fox instance

```scss
// variables.scss
$default_bg_color: #069;
$default_text_color: #eee;

// root
:root {
--navbar-background-color: #333;
--navbar-text-color: #ccc;
}

// mixins
@mixin set-bg($bg) {
  @if real-color($bg) {
    background-color: $bg;
  }
}
@mixin set-color($col) {
  @if real-color($col) {
    color: $col;
  }
}

// style
.navbar {
  @include set-bg(var(--navbar-background-color, $default_bg_color));
  @include set-color(var(--navbar-text-color, $default_text_color));
}
```

Thanks and have a good one :)
